export const SUPABASE_URL = "https://fiesjipuhvanzxudowyi.supabase.co";
export const SUPABASE_ANON_KEY =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpZXNqaXB1aHZhbnp4dWRvd3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU1NjM3OTMsImV4cCI6MjEwMTEzOTc5M30.4YYOl6CfTNuBfsM9g2kSKPyST1klVKqcz5_SQO3knoY";
